# 주문 하기
POST http://localhost:5000/api/orders
Content-Type: application/json

{
  "store_id":1
}

###
# 유저 마이페이지 주문 목록 보기
GET http://localhost:5000/api/orders/user/1

###
# 매장 관리페이지 주문 목록 보기
GET http://localhost:5000/api/orders/store/1

###
# 주문 상황 상태변경 주문접수
PATCH  http://localhost:5000/api/orders/1/1

###
# 주문 상황 상태변경 배달시작
PATCH  http://localhost:5000/api/orders/1/2

###
# 주문 상황 상태변경 배달완료
PATCH  http://localhost:5000/api/orders/1/3

###
# 주문 거절
DELETE http://localhost:5000/api/orders/1/1